# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  # Box configuration
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

  # Share an additional folder to the guest VM.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider
  config.vm.provider :aws do |aws, override|
  	aws.access_key_id = ENV['AWS_KEY']
    aws.secret_access_key = ENV['AWS_SECRET']
    aws.keypair_name = ENV['AWS_KEYPAIR_NAME']
    override.ssh.username = ENV['SSH_USERNAME']
    override.ssh.private_key_path = ENV['SSH_PRIVATE_KEY_PATH']

    aws.ami = ENV['AWS_AMI']
    aws.region = ENV['AWS_REGION']
    aws.instance_type = ENV['AWS_INSTANCE_TYPE']
    aws.security_groups = ENV['AWS_SECURITY_GROUPS']

    aws.tags = {
      'Name' => 'Vagrant'
    }
  end

  # Provisioning
end
